gitub action - test

diff --git a/.github/workflows/02.deploy.yaml b/.github/workflows/02.deploy.yaml
--- a/.github/workflows/02.deploy.yaml
+++ b/.github/workflows/02.deploy.yaml
@@ -11,8 +11,27 @@ env:
   KIND_VERSION: "0.16.0"
 
 jobs:
+  admin_check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if user is an admin
+        id: admin_check
+        env:
+          REPOSITORY: ${{ github.repository }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          user_login=$(echo ${{ github.actor }} | jq -r '.login')
+          is_admin=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/$REPOSITORY/collaborators/$user_login/permission" | jq -r '.permission')
+          if [ "$is_admin" != "admin" ]; then
+            echo "error: Only repository admins can trigger this workflow."
+            exit 1
+          else
+            echo "User is an admin. Proceeding with the workflow."
+          fi
+
   deploy:
     name: ${{ format('Deploy - {0}', github.event.inputs.tag) }}
+    needs: admin_check
     if: github.event_name == 'workflow_dispatch'
     environment: production
     runs-on: ubuntu-latest
